from Department import *

# list_degrees("./DB/Employees.db")
# add_degree("./DB/Employees.db", "Techniczne")
# add_degree("./DB/Employees.db", "Średnie")
# add_degree("./DB/Employees.db", "Inżynier")
# add_degree("./DB/Employees.db", "Magister Inżynier")
# add_degree("./DB/Employees.db", "Licencjat")
# list_degrees("./DB/Employees.db")
# edit_degree("./DB/Employees.db", "Technik", 1)
# list_degrees("./DB/Employees.db")
# delete_degree("./DB/Employees.db", 5)
# list_degrees("./DB/Employees.db")
add_department("./DB/Employees.db", "Socjalny")
add_department("./DB/Employees.db", "Dyrektor")
add_department("./DB/Employees.db", "Kuchnia")
list_department("./DB/Employees.db")
# edit_department("./DB/Employees.db", "Kuchenka", 3)
delete_department("./DB/Employees.db",2)
list_department("./DB/Employees.db")