BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Degree" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Department " (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Employees" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Surname"	TEXT NOT NULL,
	"PESEL_number"	INTEGER NOT NULL UNIQUE,
	"Degree_Id"	INTEGER NOT NULL,
	"Departemnt_Id"	INTEGER NOT NULL,
	"Room_number"	INTEGER NOT NULL,
	"Salary"	REAL NOT NULL,
	FOREIGN KEY("Departemnt_Id") REFERENCES "Department "("Id"),
	FOREIGN KEY("Degree_Id") REFERENCES "Degree"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
